<a href="https://colab.research.google.com/github/zzzer0-wav/Olist-analytics/blob/main/notebooks/olist_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Part 3. Python: Simple forecast and recommendations

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
url = 'https://raw.githubusercontent.com/zzzer0-wav/Olist-analytics/refs/heads/main/data/main_sales_reg(excel).csv'
df = pd.read_csv(url)

In [9]:
df.head()

,order_id,order_purchase_t,ym,customer_state,category_en,price,freight_value,payment_method,review_score,region
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10,SP,housewares,29.99,8.72,credit_card,4.0,Southeast
1,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10,SP,housewares,29.99,8.72,voucher,4.0,Southeast
2,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10,SP,housewares,29.99,8.72,voucher,4.0,Southeast
3,53cdb2fc8bc7dce0b6741e2150273451,2018-07-24 20:41:37,2018-07,BA,perfumery,118.70,22.76,boleto,4.0,Northeast
4,47770eb9100c2d0c44946d9cf07ec65d,2018-08-08 08:38:49,2018-08,GO,auto,159.90,19.22,credit_card,5.0,Center-West

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115723 entries, 0 to 115722
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          115723 non-null  object
 1   order_purchase_t  115723 non-null  object
 2   ym                115723 non-null  object
 3   customer_state    115723 non-null  object
 4   category_en       114062 non-null  object
 5   price             115723 non-null  float64
 6   freight_value     115723 non-null  float64
 7   payment_method    115720 non-null  object
 8   review_score      114862 non-null  float64
 9   region            115723 non-null  object
dtypes: float64(3), object(7)
memory usage: 8.8+ MB

In [23]:
miss = df.isna().sum()
miss_pct = round(df.isna().mean() * 100, 2)
missing_table = pd.DataFrame({
    'type':df.dtypes.astype(str),
    'missing': miss,
    'missing_pct':miss_pct
})

missing_table

                     type  missing  missing_pct
order_id           object        0         0.00
order_purchase_t   object        0         0.00
ym                 object        0         0.00
customer_state     object        0         0.00
category_en        object     1661         1.44
price             float64        0         0.00
freight_value     float64        0         0.00
payment_method     object        3         0.00
review_score      float64      861         0.74
region             object        0         0.00

In [20]:
df = df.sort_values('ym').reset_index(drop=True)
print('Month', len(df))
df.head()

Month 115723

,order_id,order_purchase_t,ym,customer_state,category_en,price,freight_value,payment_method,review_score,region
0,bfbd0f9bdef84302105ad712db648a6c,2016-09-15 12:16:38,2016-09,SP,health_beauty,44.99,2.83,NaN,1.0,Southeast
1,bfbd0f9bdef84302105ad712db648a6c,2016-09-15 12:16:38,2016-09,SP,health_beauty,44.99,2.83,NaN,1.0,Southeast
2,bfbd0f9bdef84302105ad712db648a6c,2016-09-15 12:16:38,2016-09,SP,health_beauty,44.99,2.83,NaN,1.0,Southeast
3,85841af0d94e5d0cd3a9c0e42e565b74,2016-10-05 22:39:46,2016-10,SP,furniture_decor,22.90,15.46,credit_card,5.0,Southeast
4,dd11631d8b02780b78bd97ec44a1ca8c,2016-10-04 23:08:08,2016-10,SP,air_conditioning,149.90,19.33,credit_card,5.0,Southeast

In [27]:
df = df[(df.ym >= '2017-01') & (df.ym <= '2018-08')].reset_index(drop=True)
print('Month (in process): ', len(df))
display(df.head(2))
df.tail(2)

Month (in process):  115385

,order_id,order_purchase_t,ym,customer_state,category_en,price,freight_value,payment_method,review_score,region
0,76774c936de5cb5a431120fde98e40da,2017-01-08 20:57:29,2017-01,SP,fashion_bags_accessories,129.99,11.38,credit_card,5.0,Southeast
1,8846a9571a893b22eb57d4732b978bbb,2017-01-26 20:44:49,2017-01,SP,perfumery,379.90,45.12,credit_card,5.0,Southeast

,order_id,order_purchase_t,ym,customer_state,category_en,price,freight_value,payment_method,review_score,region
115383,ad8c386772f88caabcff4e2a8bee26d3,2018-08-19 12:30:10,2018-08,MG,bed_bath_table,74.80,18.32,debit_card,5.0,Southeast
115384,07b1810af93ee79a38977779e7a410d0,2018-08-08 17:27:07,2018-08,ES,telephony,11.87,15.23,credit_card,3.0,Southeast

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(df.ym, df.)